services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5433/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


